### ISSUE TITLE
PR: rosbridge-server & Port forwarding configuration

### ISSUE THREAD

**Issue by jabrena** [rockstarartist/ROS-Kinetic_vagrantfile#1]
Hi @rockstarartist,

I was testing the Vagrant image and I was using the feature about port forwarded:
https://www.vagrantup.com/docs/networking/forwarded_ports.html

``` bash
Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 11311, host: 11311, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 11311, host: 11311, protocol: "udp"
end
```
I think that this line should be enable:

```
#config.vm.provision "shell", path: "catkin-workspace-setup.sh"
``` 

Any user can have multiple workspaces so this script could create the default one.

Do you accept a PR to install rosbridge:

```
sudo apt-get install ros-kinetic-rosbridge-server
``` 

I tested the installation in local with success:

```
Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 11311, host: 11311, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 11311, host: 11311, protocol: "udp"
  config.vm.network "forwarded_port", guest: 9090, host: 9090, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 9090, host: 9090, protocol: "udp"
end
``` 

**Note:** Congrats for the repo :)

Juan Antonio

**Comment by jabrena** [comment]
Note: I tested everything on `OSX` 

In the README.md you say that you couldn´t test it.

**Comment by rockstarartist** [comment]
Sorry for my late reply. Let me take a look at what you are saying.

**Comment by rockstarartist** [comment]
Okay, 

I was conflicted as to whether to leave the following line:
`#config.vm.provision "shell", path: "catkin-workspace-setup.sh"`
commented or not. I wasnt sure whether people wanted the default workspace. But i think i do agree with you, and will make it default.

Yes, i will accept the PR  to install ros-kinetic-rosbridge-server.

**Comment by jabrena** [comment]
Hi,
This weekend, i will send a PR

**Comment by rockstarartist** [comment]
No worries. I believe i have completed it all. Testing everything right now.
Currently setting up the rosbridge server as a service, so that it is up and running when everything is built into the vagrant file.
I also found an error(which i just corrected), when building the vagrant file, and the catkin-workspace-setup.sh is uncommented, the workspace fails. This is due to vagrant setting things up and not having access to the environment variables of the remote machine.

Ill have everything up, hopefully within the hour.

**Comment by rockstarartist** [comment]
Code was pushed up without the ros-bridge server setup as a service. i will have to finish this later. But the rosbridge server does get installed now.
